PruebadesdebranchHernan
analog-heart/proyectofinalE6 pull request #1
Opened 2023-06-14 19:56 UTC by analog-heart

2023-06-14 19:59 UTC, analog-heart commented
merge de prueba

2023-06-14 23:17 UTC, hhvc approved these changes

2023-06-15 04:46 UTC, analog-heart reviewed
Cuando comienzo trabaja en Rama Dev  no se puede hacar push,
Para solucionarlo debo pasarme a la rama personal  "checkout hernan-"
VERIFICAR QUE ESTOY PARADO EN MI RAMA y luego hacer "Git merge Developers"
de esta manera me estoy copiando todos los archivos de la rama develp a mi rama que estoy parado .
luego de esto podre hacer el push correspondiente !

2023-06-16 22:12 UTC, LucioCoudannes requested changes
Cambiar rama main por Developers

2023-06-16 22:14 UTC, JuanR81 requested changes
N/A

2023-06-16 22:24 UTC, LucioCoudannes approved these changes

2023-06-16 22:28 UTC, closed without merging